import { Card } from "..";

export const defaultCards: Card[] = [
  { id: "1a9x8kzq", en: "action", pt: "ação", category: "Connection - 1 - A" },
  { id: "2b7y5qsd", en: "drama", pt: "drama", category: "Connection - 1 - A" },
  {
    id: "3n2p6lrf",
    en: "romance",
    pt: "romance",
    category: "Connection - 1 - A",
  },
  {
    id: "4r8t2zkw",
    en: "adventure",
    pt: "aventura",
    category: "Connection - 1 - A",
  },
  {
    id: "5c6m7ghe",
    en: "comedy",
    pt: "comédia",
    category: "Connection - 1 - A",
  },
  {
    id: "6p4k8djr",
    en: "documentary",
    pt: "documentário",
    category: "Connection - 1 - A",
  },
  {
    id: "7x2v5bce",
    en: "horror",
    pt: "horror",
    category: "Connection - 1 - A",
  },
  { id: "8j9s6tlf", en: "crime", pt: "crime", category: "Connection - 1 - A" },
  {
    id: "9l1h3fdq",
    en: "mystery",
    pt: "mistério",
    category: "Connection - 1 - A",
  },
  {
    id: "0k2f8wue",
    en: "sci-fi",
    pt: "ficção científica",
    category: "Connection - 1 - A",
  },
  {
    id: "1v9e4qmt",
    en: "musical",
    pt: "musical",
    category: "Connection - 1 - A",
  },
  {
    id: "2r8w5yzp",
    en: "thriller",
    pt: "suspense",
    category: "Connection - 1 - A",
  },
  {
    id: "3h7d1bvx",
    en: "superhero",
    pt: "super-herói",
    category: "Connection - 1 - A",
  },
  { id: "4j2a9msl", en: "war", pt: "guerra", category: "Connection - 1 - A" },
  {
    id: "5p6z8kdm",
    en: "western",
    pt: "faroeste",
    category: "Connection - 1 - A",
  },
  {
    id: "6t3h4cvn",
    en: "cartoon, animated movie",
    pt: "desenho animado",
    category: "Connection - 1 - A",
  },
  {
    id: "7g1b9qwe",
    en: "serious",
    pt: "sério(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "8f6m5klt",
    en: "subject",
    pt: "assunto, matéria (escola)",
    category: "Connection - 1 - A",
  },
  { id: "9p7r2djc", en: "end", pt: "fim", category: "Connection - 1 - A" },
  {
    id: "0x8n3yqv",
    en: "beginning",
    pt: "início",
    category: "Connection - 1 - A",
  },
  {
    id: "1z4h6tkl",
    en: "(movie) star, to star",
    pt: "estrela, estrelar",
    category: "Connection - 1 - A",
  },
  {
    id: "2r9b7mqa",
    en: "another",
    pt: "outro(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "3n1c8zpw",
    en: "the other",
    pt: "(o/a) outro(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "4j2l6xev",
    en: "character",
    pt: "personagem",
    category: "Connection - 1 - A",
  },
  { id: "5v3h9bpt", en: "scene", pt: "cena", category: "Connection - 1 - A" },
  { id: "6m8k1fdq", en: "play", pt: "peça", category: "Connection - 1 - A" },
  {
    id: "7a4y9jwu",
    en: "playwright",
    pt: "dramaturgo(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "8s3e7rnl",
    en: "interesting",
    pt: "interessante",
    category: "Connection - 1 - A",
  },
  {
    id: "9t6h2kqp",
    en: "weird",
    pt: "estranho(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "0d9b8xfl",
    en: "scary",
    pt: "assustador(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "1k3m5vcn",
    en: "famous",
    pt: "famoso(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "2j8y9tqp",
    en: "funny",
    pt: "engraçado(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "3p5r6lwj",
    en: "exciting",
    pt: "emocionante, empolgante",
    category: "Connection - 1 - A",
  },
  {
    id: "4h2v8kzm",
    en: "short",
    pt: "curto(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "5g9x7bqt",
    en: "(the) same",
    pt: "(o) mesmo(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "6m4n2jpr",
    en: "romantic",
    pt: "romântico(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "7k1h9btq",
    en: "important",
    pt: "importante",
    category: "Connection - 1 - A",
  },
  {
    id: "8f5v3zpl",
    en: "different (from)",
    pt: "diferente (de)",
    category: "Connection - 1 - A",
  },
  {
    id: "9r2n8kjc",
    en: "suspense",
    pt: "suspense",
    category: "Connection - 1 - A",
  },
  {
    id: "0d6b4qyt",
    en: "artist",
    pt: "artista",
    category: "Connection - 1 - A",
  },
  {
    id: "1p3m7xwl",
    en: "composer",
    pt: "compositor(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "2s9h8kvr",
    en: "producer",
    pt: "produtor(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "3c4n1qmt",
    en: "director",
    pt: "diretor(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "4b8v7jkp",
    en: "classic",
    pt: "clássico",
    category: "Connection - 1 - A",
  },
  {
    id: "5h9x6dql",
    en: "writer",
    pt: "escritor(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "6r2f3pny",
    en: "long",
    pt: "longo(a)",
    category: "Connection - 1 - A",
  },
  {
    id: "g1k9t4pz",
    en: "to get in",
    pt: "entrar",
    category: "Connection - 1 - B",
  },
  {
    id: "q7m2v9as",
    en: "to get out (of)",
    pt: "sair (de)",
    category: "Connection - 1 - B",
  },
  {
    id: "b6x3n1ue",
    en: "to get",
    pt: "ficar (+adj.)",
    category: "Connection - 1 - B",
  },
  {
    id: "p8r4j2km",
    en: "to get back (from/to)",
    pt: "voltar, retornar",
    category: "Connection - 1 - B",
  },
  {
    id: "v5h9c3lw",
    en: "to get over",
    pt: "superar",
    category: "Connection - 1 - B",
  },
  {
    id: "z2f7y6dq",
    en: "to get away (from)",
    pt: "escapar, fugir",
    category: "Connection - 1 - B",
  },
  {
    id: "n4s8e5jt",
    en: "to get to do something",
    pt: "conseguir fazer algo",
    category: "Connection - 1 - B",
  },
  {
    id: "u1w6k9rb",
    en: "to get up",
    pt: "levantar",
    category: "Connection - 1 - B",
  },
  {
    id: "m7d1p3xo",
    en: "to get around",
    pt: "ir de um lugar ao outro, contornar",
    category: "Connection - 1 - B",
  },
  {
    id: "c9l5a2ty",
    en: "to get it",
    pt: "entender",
    category: "Connection - 1 - B",
  },
  {
    id: "r6j8q4we",
    en: "to get down",
    pt: "deprimir, descer",
    category: "Connection - 1 - B",
  },
  {
    id: "k3p7h1zn",
    en: "to wake up",
    pt: "acordar",
    category: "Connection - 1 - B",
  },
  {
    id: "y8b2m6fv",
    en: "to fall asleep",
    pt: "adormecer",
    category: "Connection - 1 - B",
  },
  {
    id: "t5x9n3ga",
    en: "to guess",
    pt: "adivinhar, achar",
    category: "Connection - 1 - B",
  },
  {
    id: "e2q6r7ld",
    en: "grade",
    pt: "nota (escolar)",
    category: "Connection - 1 - B",
  },
  { id: "h4u1c8sp", en: "test", pt: "teste", category: "Connection - 1 - B" },

  {
    id: "j9v3k5am",
    en: "exam",
    pt: "prova, exame",
    category: "Connection - 1 - B",
  },
  {
    id: "w6n2z8qr",
    en: "paper",
    pt: "trabalho (de escola, de faculdade)",
    category: "Connection - 1 - B",
  },
  {
    id: "d1f7y3kc",
    en: "classroom",
    pt: "sala de aula",
    category: "Connection - 1 - B",
  },
  {
    id: "s8m4p6ut",
    en: "stairs",
    pt: "escada",
    category: "Connection - 1 - B",
  },
  { id: "x5a9l2be", en: "award", pt: "prêmio", category: "Connection - 1 - B" },
  {
    id: "a3k6t7ny",
    en: "down",
    pt: "para baixo",
    category: "Connection - 1 - B",
  },
  { id: "f7r1h9ov", en: "up", pt: "para cima", category: "Connection - 1 - B" },
  {
    id: "l2c5w8jq",
    en: "inside",
    pt: "dentro (de)",
    category: "Connection - 1 - B",
  },
  {
    id: "o4p7e3mx",
    en: "outside",
    pt: "(do lado de) fora",
    category: "Connection - 1 - B",
  },
  {
    id: "g6y9b1rt",
    en: "kid",
    pt: "criança(s), filho(s)",
    category: "Connection - 1 - B",
  },
  {
    id: "q1z4u6pd",
    en: "finally",
    pt: "finalmente",
    category: "Connection - 1 - B",
  },
  { id: "b8n2m5sx", en: "still", pt: "ainda", category: "Connection - 1 - B" },
  {
    id: "p3h7v9ka",
    en: "pretty",
    pt: "bem, bastante (+adj.)",
    category: "Connection - 1 - B",
  },
  {
    id: "u9d1c4lf",
    en: "wonderful",
    pt: "maravilhoso(a)",
    category: "Connection - 1 - B",
  },
  {
    id: "m6t8e2rw",
    en: "excited",
    pt: "empolgado, animado(a)",
    category: "Connection - 1 - B",
  },
  {
    id: "c7x5q3yn",
    en: "worried",
    pt: "preocupado(a)",
    category: "Connection - 1 - B",
  },
  {
    id: "c1a9w2er",
    en: "to wear",
    pt: "usar (vestir)",
    category: "Connection - 1 - C",
  },
  {
    id: "k7p4z8md",
    en: "to put on",
    pt: "vestir",
    category: "Connection - 1 - C",
  },
  {
    id: "t9x2b6qn",
    en: "to take off",
    pt: "tirar",
    category: "Connection - 1 - C",
  },
  {
    id: "m5v1r7jl",
    en: "to try on",
    pt: "experimentar",
    category: "Connection - 1 - C",
  },
  {
    id: "f3n8h4kp",
    en: "to tie",
    pt: "amarrar",
    category: "Connection - 1 - C",
  },
  {
    id: "y2s9d5uw",
    en: "whose",
    pt: "de quem",
    category: "Connection - 1 - C",
  },
  {
    id: "q6e1j9tb",
    en: "T-shirt",
    pt: "camiseta",
    category: "Connection - 1 - C",
  },
  { id: "a8l3m2xc", en: "shirt", pt: "camisa", category: "Connection - 1 - C" },
  { id: "u4g7p1rv", en: "blouse", pt: "blusa", category: "Connection - 1 - C" },
  {
    id: "n9k6c3ze",
    en: "jacket",
    pt: "jaqueta",
    category: "Connection - 1 - C",
  },
  { id: "b7w5y2ha", en: "coat", pt: "casaco", category: "Connection - 1 - C" },
  { id: "r1d8q6om", en: "suit", pt: "terno", category: "Connection - 1 - C" },
  {
    id: "h5x9t2pv",
    en: "sweater",
    pt: "suéter, blusa",
    category: "Connection - 1 - C",
  },
  {
    id: "p2c7f4nk",
    en: "sweatshirt, sweatpants",
    pt: "blusa e calça de moletom",
    category: "Connection - 1 - C",
  },
  {
    id: "e6m3z8qy",
    en: "hoodie",
    pt: "casaco de moletom com capuz",
    category: "Connection - 1 - C",
  },
  {
    id: "v3j1k7sa",
    en: "dress",
    pt: "vestido",
    category: "Connection - 1 - C",
  },
  { id: "x8t5n2rl", en: "skirt", pt: "saia", category: "Connection - 1 - C" },
  { id: "g4a9b6uw", en: "pants", pt: "calças", category: "Connection - 1 - C" },

  { id: "z1m7p3qd", en: "shorts", pt: "short", category: "Connection - 1 - C" },
  {
    id: "s5k2v9hj",
    en: "underwear",
    pt: "roupa íntima",
    category: "Connection - 1 - C",
  },
  { id: "d9f6r1xe", en: "briefs", pt: "cueca", category: "Connection - 1 - C" },
  {
    id: "j6y4c8np",
    en: "panties",
    pt: "calcinha",
    category: "Connection - 1 - C",
  },
  { id: "l2q8h7to", en: "bra", pt: "soutien", category: "Connection - 1 - C" },
  { id: "w9u3e5km", en: "socks", pt: "meias", category: "Connection - 1 - C" },
  {
    id: "o7r1n6bf",
    en: "pantyhose, tights",
    pt: "meia-calça",
    category: "Connection - 1 - C",
  },
  { id: "i3p9t2cv", en: "tie", pt: "gravata", category: "Connection - 1 - C" },
  { id: "k8h4z1wa", en: "belt", pt: "cinto", category: "Connection - 1 - C" },
  { id: "c6s2m7yd", en: "hat", pt: "chapéu", category: "Connection - 1 - C" },
  { id: "t1x5g8rl", en: "cap", pt: "boné", category: "Connection - 1 - C" },
  {
    id: "m5e2q9uj",
    en: "glasses, sunglasses",
    pt: "óculos, óculos escuros",
    category: "Connection - 1 - C",
  },
  {
    id: "y7b3v1nk",
    en: "flip flops",
    pt: "chinelo de dedos",
    category: "Connection - 1 - C",
  },
  {
    id: "f2n8a6pt",
    en: "slippers",
    pt: "chinelos, pantufas",
    category: "Connection - 1 - C",
  },
  {
    id: "a4w7r3xe",
    en: "sneakers, tennis shoes",
    pt: "tênis",
    category: "Connection - 1 - C",
  },
  { id: "u8k1d5gz", en: "boots", pt: "botas", category: "Connection - 1 - C" },
  {
    id: "n3h6q2lm",
    en: "pajamas",
    pt: "pijama",
    category: "Connection - 1 - C",
  },
  {
    id: "b9v4t1co",
    en: "nightgown",
    pt: "camisola",
    category: "Connection - 1 - C",
  },

  { id: "r4j8m2ps", en: "size", pt: "tamanho", category: "Connection - 1 - C" },
  {
    id: "h6q3z9wa",
    en: "swimming trunks",
    pt: "shorts de banho",
    category: "Connection - 1 - C",
  },
  {
    id: "p1d5e7vk",
    en: "boxer",
    pt: "samba canção",
    category: "Connection - 1 - C",
  },
  { id: "e7m2x4ny", en: "medium", pt: "médio", category: "Connection - 1 - C" },
  {
    id: "v2k9c6rt",
    en: "bikini",
    pt: "biquini",
    category: "Connection - 1 - C",
  },
  {
    id: "x5t1g8qb",
    en: "boxer briefs",
    pt: "cueca boxer",
    category: "Connection - 1 - C",
  },
  { id: "g3a7w2lu", en: "large", pt: "grande", category: "Connection - 1 - C" },
  {
    id: "z8n4p6dj",
    en: "bathing/swimming suit",
    pt: "maiô, roupas de banho",
    category: "Connection - 1 - C",
  },
  {
    id: "s6y1f3hm",
    en: "sleeve, long-sleeved",
    pt: "manga, de manga longa",
    category: "Connection - 1 - C",
  },
  { id: "d2k8r5xc", en: "jeans", pt: "jeans", category: "Connection - 1 - C" },
  {
    id: "j9u3e7tw",
    en: "uniform",
    pt: "uniforme",
    category: "Connection - 1 - C",
  },
  {
    id: "l1c5m9ya",
    en: "sleeveless shirt, tank top",
    pt: "camiseta sem manga",
    category: "Connection - 1 - C",
  },
  { id: "w7r2h4pn", en: "vest", pt: "colete", category: "Connection - 1 - C" },
  {
    id: "o5q9t3kv",
    en: "shoelaces",
    pt: "cadarço",
    category: "Connection - 1 - C",
  },
  {
    id: "d1k8r3pn",
    en: "are going to",
    pt: "vão",
    category: "Connection - 1 - D",
  },
  {
    id: "x6m4t9we",
    en: "experience",
    pt: "experiência",
    category: "Connection - 1 - D",
  },
  {
    id: "b3h1v7ql",
    en: "in which",
    pt: "no qual",
    category: "Connection - 1 - D",
  },
  { id: "t9s5e2mv", en: "dies", pt: "morre", category: "Connection - 1 - D" },
  {
    id: "f7a2n6kp",
    en: "puppies",
    pt: "filhotes de cachorro",
    category: "Connection - 1 - D",
  },
  { id: "n4z3w8rb", en: "villain", pt: "vilã", category: "Connection - 1 - D" },
  { id: "j8p6d1yc", en: "had", pt: "teve", category: "Connection - 1 - D" },
  {
    id: "k2m9x5tf",
    en: "was crying",
    pt: "estava chorando",
    category: "Connection - 1 - D",
  },
  {
    id: "a5v7n3gl",
    en: "actually",
    pt: "realmente",
    category: "Connection - 1 - D",
  },
  { id: "u9q1r8so", en: "kill", pt: "matar", category: "Connection - 1 - D" },

  { id: "e4y6t9hp", en: "fur", pt: "pele", category: "Connection - 1 - D" },
  {
    id: "z7b2k5wd",
    en: "choice",
    pt: "escolha",
    category: "Connection - 1 - D",
  },
  {
    id: "m1c9x3lf",
    en: "controversy",
    pt: "controvérsia",
    category: "Connection - 1 - D",
  },
  {
    id: "r8p4v6tn",
    en: "British",
    pt: "britânico",
    category: "Connection - 1 - D",
  },
  {
    id: "g3q7s1ae",
    en: "talk back",
    pt: "responder",
    category: "Connection - 1 - D",
  },
  {
    id: "y5d2h8km",
    en: "make fun",
    pt: "zombar",
    category: "Connection - 1 - D",
  },
  {
    id: "c9n6p4jx",
    en: "even",
    pt: "até mesmo",
    category: "Connection - 1 - D",
  },
  {
    id: "w1t8v7rz",
    en: "banned",
    pt: "banido",
    category: "Connection - 1 - D",
  },
  { id: "l4k5m9uq", en: "best", pt: "melhor", category: "Connection - 1 - D" },
  {
    id: "p2s3f6ov",
    en: "decide",
    pt: "decidir",
    category: "Connection - 1 - D",
  },
  {
    id: "p9x4k2jm",
    en: "to remember",
    pt: "lembrar",
    category: "Connection - 2 - A",
  },
  {
    id: "v3n8s6qa",
    en: "to forget",
    pt: "esquecer",
    category: "Connection - 2 - A",
  },
  {
    id: "k7r1b9tw",
    en: "to lose",
    pt: "perder",
    category: "Connection - 2 - A",
  },
  {
    id: "m4d2h8zf",
    en: "to miss",
    pt: "perder, sentir falta/saudades",
    category: "Connection - 2 - A",
  },
  {
    id: "b6u3e7cy",
    en: "to hear",
    pt: "ouvir",
    category: "Connection - 2 - A",
  },
  {
    id: "t1q9w5le",
    en: "to cry",
    pt: "chorar",
    category: "Connection - 2 - A",
  },
  {
    id: "g2h7p4vx",
    en: "to bark",
    pt: "latir",
    category: "Connection - 2 - A",
  },
  {
    id: "r5k8n3yd",
    en: "to walk the dog",
    pt: "passear com o cachorro",
    category: "Connection - 2 - A",
  },
  {
    id: "c8j1x6mw",
    en: "to ring",
    pt: "tocar (campainha, telefone)",
    category: "Connection - 2 - A",
  },
  {
    id: "y4f7a2pn",
    en: "to answer",
    pt: "atender",
    category: "Connection - 2 - A",
  },
  {
    id: "e6z3m9kt",
    en: "to oversleep",
    pt: "dormir demais",
    category: "Connection - 2 - A",
  },
  {
    id: "n2p8r5hv",
    en: "to have no idea",
    pt: "não ter ideia, não saber",
    category: "Connection - 2 - A",
  },
  {
    id: "w7l1c4sq",
    en: "yesterday",
    pt: "ontem",
    category: "Connection - 2 - A",
  },
  {
    id: "a5u9d3je",
    en: "the day before yesterday",
    pt: "anteontem",
    category: "Connection - 2 - A",
  },
  {
    id: "h9m6v1bo",
    en: "last night",
    pt: "ontem à noite",
    category: "Connection - 2 - A",
  },

  { id: "z3x8k5lt", en: "ago", pt: "atrás", category: "Connection - 2 - A" },
  { id: "q6r2n7yb", en: "alarm", pt: "alarme", category: "Connection - 2 - A" },
  {
    id: "j1d5f9pw",
    en: "clock",
    pt: "relógio",
    category: "Connection - 2 - A",
  },
  {
    id: "s8o4m2ga",
    en: "watch",
    pt: "relógio de pulso",
    category: "Connection - 2 - A",
  },
  { id: "l2k7e5rc", en: "key", pt: "chave", category: "Connection - 2 - A" },
  {
    id: "u9a3t6hv",
    en: "noise",
    pt: "barulho",
    category: "Connection - 2 - A",
  },
  {
    id: "d4p1w7xn",
    en: "upstairs",
    pt: "andar de cima",
    category: "Connection - 2 - A",
  },
  {
    id: "f7c2b9me",
    en: "downstairs",
    pt: "andar de baixo",
    category: "Connection - 2 - A",
  },
  {
    id: "o1v6j4ty",
    en: "strange",
    pt: "estranho",
    category: "Connection - 2 - A",
  },
  { id: "i5g9q3ku", en: "low", pt: "baixo", category: "Connection - 2 - A" },
  {
    id: "p4h8n6zw",
    en: "loud",
    pt: "alto (som)",
    category: "Connection - 2 - A",
  },
  {
    id: "x7m3c1ra",
    en: "hurry up",
    pt: "se apresse",
    category: "Connection - 2 - A",
  },
  {
    id: "k3e6y8vd",
    en: "in a hurry",
    pt: "com pressa",
    category: "Connection - 2 - A",
  },
  {
    id: "m6t9s2bf",
    en: "come on",
    pt: "vamos",
    category: "Connection - 2 - A",
  },

  {
    id: "b1n4y7qc",
    en: "a long time ago",
    pt: "muito tempo atrás",
    category: "Connection - 2 - A",
  },
  {
    id: "t2w5k8le",
    en: "long ago",
    pt: "tempos atrás",
    category: "Connection - 2 - A",
  },
  {
    id: "r3h6p9vm",
    en: "last week, month, year",
    pt: "semana, mês, ano passado",
    category: "Connection - 2 - A",
  },
  {
    id: "c4j7x1sd",
    en: "decade",
    pt: "década",
    category: "Connection - 2 - A",
  },
  {
    id: "v5m8a2gn",
    en: "century",
    pt: "século",
    category: "Connection - 2 - A",
  },
  {
    id: "a1k9t4pm",
    en: "to believe",
    pt: "acreditar",
    category: "Connection - 2 - B",
  },
  {
    id: "b7v2m9qs",
    en: "to trust",
    pt: "confiar",
    category: "Connection - 2 - B",
  },
  {
    id: "c6x3n1ue",
    en: "to lie",
    pt: "mentir",
    category: "Connection - 2 - B",
  },
  {
    id: "d8r4j2km",
    en: "to promise",
    pt: "prometer",
    category: "Connection - 2 - B",
  },
  {
    id: "e5h9c3lw",
    en: "to make up",
    pt: "inventar",
    category: "Connection - 2 - B",
  },
  {
    id: "f2z7y6dq",
    en: "to remind (of)",
    pt: "lembrar, fazer lembrar",
    category: "Connection - 2 - B",
  },
  {
    id: "g4s8e5jt",
    en: "to feel",
    pt: "sentir",
    category: "Connection - 2 - B",
  },
  {
    id: "h1w6k9rb",
    en: "to notice",
    pt: "reparar, notar, perceber",
    category: "Connection - 2 - B",
  },
  {
    id: "i7d1p3xo",
    en: "to smell",
    pt: "cheirar",
    category: "Connection - 2 - B",
  },
  { id: "j9l5a2ty", en: "smell", pt: "cheiro", category: "Connection - 2 - B" },
  {
    id: "k6j8q4we",
    en: "used to",
    pt: "costumava",
    category: "Connection - 2 - B",
  },
  {
    id: "l3p7h1zn",
    en: "true",
    pt: "verdadeiro(a)",
    category: "Connection - 2 - B",
  },
  {
    id: "m8b2m6fv",
    en: "false, fake",
    pt: "falso(a)",
    category: "Connection - 2 - B",
  },
  {
    id: "n5x9n3ga",
    en: "truth",
    pt: "verdade",
    category: "Connection - 2 - B",
  },
  { id: "o2q6r7ld", en: "lie", pt: "mentira", category: "Connection - 2 - B" },
  {
    id: "p4u1c8sp",
    en: "liar",
    pt: "mentiroso(a)",
    category: "Connection - 2 - B",
  },
  {
    id: "q9v3k5am",
    en: "promise",
    pt: "promessa",
    category: "Connection - 2 - B",
  },
  {
    id: "r6n2z8qr",
    en: "feeling",
    pt: "sentimento",
    category: "Connection - 2 - B",
  },

  { id: "s1f7y3kc", en: "angel", pt: "anjo", category: "Connection - 2 - B" },
  {
    id: "t8m4p6ut",
    en: "ghost",
    pt: "fantasma",
    category: "Connection - 2 - B",
  },
  { id: "u5a9l2be", en: "witch", pt: "bruxa", category: "Connection - 2 - B" },
  { id: "v3k6t7ny", en: "God", pt: "Deus", category: "Connection - 2 - B" },
  {
    id: "w7y4c8np",
    en: "Santa Claus",
    pt: "Papai Noel",
    category: "Connection - 2 - B",
  },
  { id: "x2q8h7to", en: "dream", pt: "sonho", category: "Connection - 2 - B" },
  {
    id: "y9u3e5km",
    en: "nightmare",
    pt: "pesadelo",
    category: "Connection - 2 - B",
  },
  {
    id: "z7r1n6bf",
    en: "candy",
    pt: "bala, doces",
    category: "Connection - 2 - B",
  },
  {
    id: "a0p9t2cv",
    en: "curious",
    pt: "curioso(a)",
    category: "Connection - 2 - B",
  },
  {
    id: "b8h4z1wa",
    en: "what's the matter?",
    pt: "qual é o problema?",
    category: "Connection - 2 - B",
  },
  {
    id: "c6s2m7yd",
    en: "what a shame, what a pity",
    pt: "que pena",
    category: "Connection - 2 - B",
  },
  {
    id: "d1x5g8rl",
    en: "shame",
    pt: "pena, vergonha",
    category: "Connection - 2 - B",
  },
  {
    id: "e5e2q9uj",
    en: "too bad",
    pt: "que pena",
    category: "Connection - 2 - B",
  },
  {
    id: "f3b3v1nk",
    en: "never mind",
    pt: "deixa pra lá",
    category: "Connection - 2 - B",
  },
  {
    id: "g9n8a6pt",
    en: "absolutely",
    pt: "absolutamente, realmente, sem dúvida",
    category: "Connection - 2 - B",
  },
  {
    id: "h4w7r3xe",
    en: "absolutely not",
    pt: "de jeito nenhum",
    category: "Connection - 2 - B",
  },
  {
    id: "i8k1d5gz",
    en: "probably",
    pt: "provavelmente",
    category: "Connection - 2 - B",
  },
  {
    id: "j3h6q2lm",
    en: "anymore",
    pt: "(não) mais",
    category: "Connection - 2 - B",
  },
  {
    id: "c2a9w1er",
    en: "to enjoy",
    pt: "gostar, desfrutar",
    category: "Connection - 2 - C",
  },
  {
    id: "k7p4z8md",
    en: "to mean",
    pt: "significar, querer dizer",
    category: "Connection - 2 - C",
  },
  {
    id: "t9x2b6qn",
    en: "to change",
    pt: "mudar, trocar",
    category: "Connection - 2 - C",
  },
  {
    id: "m5v1r7jl",
    en: "to exchange",
    pt: "trocar",
    category: "Connection - 2 - C",
  },
  {
    id: "f3n8h4kp",
    en: "to stand (up)",
    pt: "ficar de pé, levantar-se",
    category: "Connection - 2 - C",
  },
  {
    id: "y2s9d5uw",
    en: "to move",
    pt: "mudar-se, mover-se",
    category: "Connection - 2 - C",
  },
  {
    id: "q6e1j9tb",
    en: "to laugh (at)",
    pt: "rir",
    category: "Connection - 2 - C",
  },
  {
    id: "a8l3m2xc",
    en: "somebody, someone",
    pt: "alguém",
    category: "Connection - 2 - C",
  },
  {
    id: "u4g7p1rv",
    en: "anybody, anyone",
    pt: "alguém, ninguém, qualquer um",
    category: "Connection - 2 - C",
  },
  {
    id: "n9k6c3ze",
    en: "nobody, no one",
    pt: "ninguém",
    category: "Connection - 2 - C",
  },
  {
    id: "b7w5y2ha",
    en: "everybody, everyone",
    pt: "todo mundo",
    category: "Connection - 2 - C",
  },
  {
    id: "r1d8q6om",
    en: "like, as",
    pt: "como",
    category: "Connection - 2 - C",
  },
  { id: "h5x9t2pv", en: "if", pt: "se", category: "Connection - 2 - C" },
  { id: "p2c7f4nk", en: "trip", pt: "viagem", category: "Connection - 2 - C" },
  { id: "e6m3z8qy", en: "joke", pt: "piada", category: "Connection - 2 - C" },
  { id: "v3j1k7sa", en: "line", pt: "fila", category: "Connection - 2 - C" },
  {
    id: "x8t5n2rl",
    en: "bag",
    pt: "bolsa, sacola",
    category: "Connection - 2 - C",
  },

  { id: "g4a9b6uw", en: "purse", pt: "bolsa", category: "Connection - 2 - C" },
  {
    id: "z1m7p3qd",
    en: "backpack",
    pt: "mochila",
    category: "Connection - 2 - C",
  },
  {
    id: "s5k2v9hj",
    en: "wallet",
    pt: "carteira",
    category: "Connection - 2 - C",
  },
  {
    id: "d9f6r1xe",
    en: "plastic bag",
    pt: "sacola plástica",
    category: "Connection - 2 - C",
  },
  {
    id: "j6y4c8np",
    en: "paper bag",
    pt: "sacola de papel",
    category: "Connection - 2 - C",
  },
  {
    id: "l2q8h7to",
    en: "leather",
    pt: "couro",
    category: "Connection - 2 - C",
  },
  {
    id: "w9u3e5km",
    en: "free",
    pt: "de graça, livre",
    category: "Connection - 2 - C",
  },
  {
    id: "o7r1n6bf",
    en: "modern",
    pt: "moderno(a)",
    category: "Connection - 2 - C",
  },
  {
    id: "i3p9t2cv",
    en: "outdated",
    pt: "fora de moda, antigo",
    category: "Connection - 2 - C",
  },
  {
    id: "k8h4z1wa",
    en: "comfortable",
    pt: "confortável",
    category: "Connection - 2 - C",
  },
  {
    id: "c6s2m7yd",
    en: "uncomfortable",
    pt: "desconfortável",
    category: "Connection - 2 - C",
  },
  {
    id: "t1x5g8rl",
    en: "perfect",
    pt: "perfeito",
    category: "Connection - 2 - C",
  },
  { id: "m5e2q9uj", en: "fashion", pt: "moda", category: "Connection - 2 - C" },
  {
    id: "y7b3v1nk",
    en: "air conditioning, air conditioner",
    pt: "ar condicionado",
    category: "Connection - 2 - C",
  },
  {
    id: "f2n8a6pt",
    en: "lady, ma'am (madam)",
    pt: "senhora",
    category: "Connection - 2 - C",
  },
  {
    id: "a4w7r3xe",
    en: "gentleman, sir",
    pt: "senhor",
    category: "Connection - 2 - C",
  },
  {
    id: "a7r3t9lm",
    en: "weather",
    pt: "clima, tempo",
    category: "Connection - 2 - D",
  },
  { id: "b6n8p2qv", en: "was", pt: "estava", category: "Connection - 2 - D" },
  {
    id: "c9h1k4we",
    en: "complains",
    pt: "reclama",
    category: "Connection - 2 - D",
  },
  { id: "d5f7y3ao", en: "even", pt: "até", category: "Connection - 2 - D" },
  {
    id: "e2m9x6tp",
    en: "a bit",
    pt: "um pouco",
    category: "Connection - 2 - D",
  },
  {
    id: "f4j8c1rn",
    en: "we'll return",
    pt: "retornaremos",
    category: "Connection - 2 - D",
  },
  {
    id: "a1k9t4pm",
    en: "to be able to",
    pt: "ser capaz de, poder",
    category: "Connection - 3 - A",
  },
  {
    id: "b7v2m9qs",
    en: "to be surprised (at)",
    pt: "estar surpreso(a) com",
    category: "Connection - 3 - A",
  },
  {
    id: "c6x3n1ue",
    en: "to be interested in",
    pt: "ser/estar interessado(a) em",
    category: "Connection - 3 - A",
  },
  {
    id: "d8r4j2km",
    en: "to be pleased with",
    pt: "estar satisfeito(a) com",
    category: "Connection - 3 - A",
  },
  {
    id: "e5h9c3lw",
    en: "to be born",
    pt: "nascer",
    category: "Connection - 3 - A",
  },
  {
    id: "f2z7y6dq",
    en: "to be in love",
    pt: "estar apaixonado(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "g4s8e5jt",
    en: "to become",
    pt: "tornar-se",
    category: "Connection - 3 - A",
  },
  {
    id: "h1w6k9rb",
    en: "to hope",
    pt: "esperar (ter esperança)",
    category: "Connection - 3 - A",
  },
  {
    id: "i7d1p3xo",
    en: "to die",
    pt: "morrer",
    category: "Connection - 3 - A",
  },
  {
    id: "j9l5a2ty",
    en: "to date",
    pt: "namorar, sair com uma pessoa",
    category: "Connection - 3 - A",
  },
  {
    id: "k6j8q4we",
    en: "possible",
    pt: "possível",
    category: "Connection - 3 - A",
  },
  {
    id: "l3p7h1zn",
    en: "impossible",
    pt: "impossível",
    category: "Connection - 3 - A",
  },
  {
    id: "m8b2m6fv",
    en: "fancy",
    pt: "elegante",
    category: "Connection - 3 - A",
  },
  {
    id: "n5x9n3ga",
    en: "imported",
    pt: "importado(a)",
    category: "Connection - 3 - A",
  },
  { id: "o2q6r7ld", en: "poor", pt: "pobre", category: "Connection - 3 - A" },
  { id: "p4u1c8sp", en: "rich", pt: "rico(a)", category: "Connection - 3 - A" },
  {
    id: "q9v3k5am",
    en: "busy",
    pt: "ocupado(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "r6n2z8qr",
    en: "in a good mood",
    pt: "de bom humor",
    category: "Connection - 3 - A",
  },

  {
    id: "s1f7y3kc",
    en: "in a bad mood",
    pt: "de mau humor",
    category: "Connection - 3 - A",
  },
  {
    id: "t8m4p6ut",
    en: "welcome",
    pt: "bem-vindo(a)",
    category: "Connection - 3 - A",
  },
  { id: "u5a9l2be", en: "course", pt: "curso", category: "Connection - 3 - A" },
  { id: "v3k6t7ny", en: "ride", pt: "carona", category: "Connection - 3 - A" },
  {
    id: "w7y4c8np",
    en: "date",
    pt: "encontro",
    category: "Connection - 3 - A",
  },
  {
    id: "x2q8h7to",
    en: "result",
    pt: "resultado",
    category: "Connection - 3 - A",
  },
  {
    id: "y9u3e5km",
    en: "accident",
    pt: "acidente",
    category: "Connection - 3 - A",
  },
  {
    id: "z7r1n6bf",
    en: "in time",
    pt: "a tempo",
    category: "Connection - 3 - A",
  },
  {
    id: "a0p9t2cv",
    en: "on time",
    pt: "na hora",
    category: "Connection - 3 - A",
  },
  {
    id: "b8h4z1wa",
    en: "guest",
    pt: "convidado, hóspede",
    category: "Connection - 3 - A",
  },
  {
    id: "c6s2m7yd",
    en: "be my guest",
    pt: "fique à vontade",
    category: "Connection - 3 - A",
  },
  {
    id: "d1x5g8rl",
    en: "host, hostess",
    pt: "anfitrião, anfitriã",
    category: "Connection - 3 - A",
  },
  {
    id: "e5e2q9uj",
    en: "dead",
    pt: "morto(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "f3b3v1nk",
    en: "alive",
    pt: "vivo(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "g9n8a6pt",
    en: "left, leftover",
    pt: "sobrando, sobra",
    category: "Connection - 3 - A",
  },
  {
    id: "h4w7r3xe",
    en: "full",
    pt: "cheio(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "i8k1d5gz",
    en: "empty",
    pt: "vazio(a)",
    category: "Connection - 3 - A",
  },
  {
    id: "n1x9c2ta",
    en: "to draw",
    pt: "desenhar, fechar cortinas",
    category: "Connection - 3 - B",
  },
  {
    id: "s8d0v5ke",
    en: "to paint",
    pt: "pintar",
    category: "Connection - 3 - B",
  },
  {
    id: "a4f7z0um",
    en: "to plant",
    pt: "plantar",
    category: "Connection - 3 - B",
  },
  {
    id: "j2l6y9bs",
    en: "to take pictures, photographs",
    pt: "tirar fotos",
    category: "Connection - 3 - B",
  },
  {
    id: "r9q3b8da",
    en: "picture",
    pt: "figura, imagem, foto",
    category: "Connection - 3 - B",
  },
  {
    id: "p7s1g6fv",
    en: "forest",
    pt: "floresta",
    category: "Connection - 3 - B",
  },
  { id: "c5m8h2wl", en: "hill", pt: "morro", category: "Connection - 3 - B" },
  {
    id: "e0y4b1uq",
    en: "mountain",
    pt: "montanha",
    category: "Connection - 3 - B",
  },
  {
    id: "v3j5n9xr",
    en: "waterfall",
    pt: "cachoeira",
    category: "Connection - 3 - B",
  },
  { id: "z2t8p4kc", en: "river", pt: "rio", category: "Connection - 3 - B" },
  { id: "b4k1f0lj", en: "lake", pt: "lago", category: "Connection - 3 - B" },
  { id: "q8n5r3ve", en: "sea", pt: "mar", category: "Connection - 3 - B" },
  { id: "u7c9z6sd", en: "grass", pt: "grama", category: "Connection - 3 - B" },
  { id: "k2d1m5aw", en: "yard", pt: "quintal", category: "Connection - 3 - B" },
  {
    id: "x9r4l2bt",
    en: "garden",
    pt: "jardim, horta",
    category: "Connection - 3 - B",
  },
  { id: "m3f8s7qe", en: "tree", pt: "árvore", category: "Connection - 3 - B" },
  {
    id: "t1p9h4cz",
    en: "bugs, insects",
    pt: "insetos",
    category: "Connection - 3 - B",
  },
  {
    id: "w0b7y2la",
    en: "cockroach, roach",
    pt: "barata",
    category: "Connection - 3 - B",
  },
  {
    id: "g2z4p5rh",
    en: "butterfly",
    pt: "borboleta",
    category: "Connection - 3 - B",
  },
  { id: "l9c6f1qx", en: "fly", pt: "mosca", category: "Connection - 3 - B" },
  { id: "y4t2s0mn", en: "bee", pt: "abelha", category: "Connection - 3 - B" },
  {
    id: "o8j5v7rk",
    en: "spider",
    pt: "aranha",
    category: "Connection - 3 - B",
  },
  {
    id: "d3a9n4xe",
    en: "frog",
    pt: "sapo, rã",
    category: "Connection - 3 - B",
  },
  { id: "f6q1k9uj", en: "snake", pt: "cobra", category: "Connection - 3 - B" },
  { id: "i7p3b8sd", en: "bridge", pt: "ponte", category: "Connection - 3 - B" },
  { id: "h5r2c0tl", en: "tunnel", pt: "túnel", category: "Connection - 3 - B" },
  {
    id: "a9x4y6we",
    en: "castle",
    pt: "castelo",
    category: "Connection - 3 - B",
  },
  { id: "s0n8l3zp", en: "boat", pt: "barco", category: "Connection - 3 - B" },
  { id: "e2v5j9mr", en: "ship", pt: "navio", category: "Connection - 3 - B" },
  {
    id: "p1k6d4qa",
    en: "camera",
    pt: "câmera",
    category: "Connection - 3 - B",
  },
  {
    id: "z8s9f7cn",
    en: "several",
    pt: "vários",
    category: "Connection - 3 - B",
  },
  {
    id: "r5q3m2lu",
    en: "even",
    pt: "mesmo, até mesmo, ainda(mais)",
    category: "Connection - 3 - B",
  },
  {
    id: "j4y1v9bd",
    en: "through, thru",
    pt: "através",
    category: "Connection - 3 - B",
  },
  {
    id: "n6a5p8wt",
    en: "over, above",
    pt: "acima, sobre",
    category: "Connection - 3 - B",
  },
  {
    id: "u3f7r2kx",
    en: "by, alongside",
    pt: "ao lado",
    category: "Connection - 3 - B",
  },
  {
    id: "t0c9h4mz",
    en: "a few, few",
    pt: "poucos",
    category: "Connection - 3 - B",
  },
  {
    id: "k7l2q5nd",
    en: "nature",
    pt: "natureza",
    category: "Connection - 3 - B",
  },
  { id: "x4p6m1sf", en: "jungle", pt: "selva", category: "Connection - 3 - B" },
  {
    id: "v9b8r0jq",
    en: "woods",
    pt: "bosque, mata",
    category: "Connection - 3 - B",
  },
  { id: "b2z5y3ta", en: "ocean", pt: "oceano", category: "Connection - 3 - B" },
  {
    id: "g1x7k9ue",
    en: "drawing",
    pt: "desenho",
    category: "Connection - 3 - B",
  },
  {
    id: "m3h4c6rl",
    en: "mosquito",
    pt: "mosquito",
    category: "Connection - 3 - B",
  },
  {
    id: "a5p9t8yv",
    en: "painter",
    pt: "pintor",
    category: "Connection - 3 - B",
  },
  {
    id: "a1t9k4mv",
    en: "to smile",
    pt: "sorrir",
    category: "Connection - 3 - C",
  },
  {
    id: "f8r2n7qh",
    en: "to grow, to grow up",
    pt: "crescer",
    category: "Connection - 3 - C",
  },
  {
    id: "j4b5y9ca",
    en: "to rain",
    pt: "chover",
    category: "Connection - 3 - C",
  },
  {
    id: "p0s8x3dl",
    en: "to try",
    pt: "tentar",
    category: "Connection - 3 - C",
  },
  {
    id: "v7e1q6zr",
    en: "to hold",
    pt: "segurar, abraçar",
    category: "Connection - 3 - C",
  },
  {
    id: "n3k5m9tx",
    en: "to feed",
    pt: "alimentar",
    category: "Connection - 3 - C",
  },
  {
    id: "l2w8c4js",
    en: "to fish",
    pt: "pescar",
    category: "Connection - 3 - C",
  },
  {
    id: "b9d1r7ue",
    en: "to water",
    pt: "regar",
    category: "Connection - 3 - C",
  },
  {
    id: "x6f4h0pn",
    en: "to drown",
    pt: "afogar-se",
    category: "Connection - 3 - C",
  },
  {
    id: "u5c3z8yb",
    en: "to save",
    pt: "salvar, economizar",
    category: "Connection - 3 - C",
  },
  {
    id: "r1v9t7gw",
    en: "childhood",
    pt: "infância",
    category: "Connection - 3 - C",
  },
  {
    id: "h0s6p4le",
    en: "adult, grown-up",
    pt: "adulto",
    category: "Connection - 3 - C",
  },
  {
    id: "m2k8q1dz",
    en: "teenager, adolescent",
    pt: "adolescente",
    category: "Connection - 3 - C",
  },
  {
    id: "c9n3b5vx",
    en: "floor",
    pt: "andar (de prédio), chão",
    category: "Connection - 3 - C",
  },
  {
    id: "g4l2y8tf",
    en: "story, stories",
    pt: "andar (de casa), história",
    category: "Connection - 3 - C",
  },
  { id: "e5w7h9ka", en: "sun", pt: "sol", category: "Connection - 3 - C" },
  { id: "z8p3d6mq", en: "moon", pt: "lua", category: "Connection - 3 - C" },
  {
    id: "t9f1x0rn",
    en: "light",
    pt: "luz, leve, claro(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "y2s4g8jw",
    en: "umbrella",
    pt: "guarda-chuva",
    category: "Connection - 3 - C",
  },
  { id: "k5a0b9lh", en: "dry", pt: "seco(a)", category: "Connection - 3 - C" },
  {
    id: "d1v7p6ze",
    en: "wet",
    pt: "molhado(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "a3n9r4tu",
    en: "noisy",
    pt: "barulhento(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "s7m5y1cx",
    en: "crowded",
    pt: "lotado(a), muito cheio(de gente)",
    category: "Connection - 3 - C",
  },
  {
    id: "q4h8v2jp",
    en: "advantage",
    pt: "vantagem",
    category: "Connection - 3 - C",
  },
  {
    id: "p6x3l9de",
    en: "disadvantage",
    pt: "desvantagem",
    category: "Connection - 3 - C",
  },
  {
    id: "n8t2b7wf",
    en: "nervous",
    pt: "nervoso(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "r5q9m4za",
    en: "calm",
    pt: "calmo(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "g0k6s8by",
    en: "upset",
    pt: "chateado(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "x1f7c9hv",
    en: "fast, quick",
    pt: "rápido(a)",
    category: "Connection - 3 - C",
  },
  { id: "m4w3p5le", en: "slow", pt: "devagar", category: "Connection - 3 - C" },
  {
    id: "j2b8t9qk",
    en: "glad",
    pt: "contente, feliz",
    category: "Connection - 3 - C",
  },
  { id: "e6y4n0sr", en: "huge", pt: "enorme", category: "Connection - 3 - C" },
  { id: "l5p1v9zc", en: "almost", pt: "quase", category: "Connection - 3 - C" },
  {
    id: "f3x7g2nd",
    en: "though",
    pt: "embora, no entanto, mas",
    category: "Connection - 3 - C",
  },
  { id: "b8r6m0uw", en: "each", pt: "cada", category: "Connection - 3 - C" },
  {
    id: "k1d9y3aq",
    en: "while",
    pt: "enquanto",
    category: "Connection - 3 - C",
  },
  { id: "c4s2z8tv", en: "cow", pt: "vaca", category: "Connection - 3 - C" },
  { id: "h7m9f5lx", en: "bull", pt: "touro", category: "Connection - 3 - C" },
  { id: "z0p4y1nr", en: "duck", pt: "pato", category: "Connection - 3 - C" },
  {
    id: "u2v8c6je",
    en: "chicken, hen",
    pt: "galinha",
    category: "Connection - 3 - C",
  },
  { id: "t3k7s9wa", en: "rooster", pt: "galo", category: "Connection - 3 - C" },
  {
    id: "g9f1l5pq",
    en: "chick",
    pt: "pintinho",
    category: "Connection - 3 - C",
  },
  { id: "a8r0d7xe", en: "pig", pt: "porco", category: "Connection - 3 - C" },
  {
    id: "y6n3h9wb",
    en: "goose, geese",
    pt: "ganso, gansos",
    category: "Connection - 3 - C",
  },
  {
    id: "r2p5q8md",
    en: "rabbit, bunny",
    pt: "coelho, coelhinho",
    category: "Connection - 3 - C",
  },
  {
    id: "x9v7l1tk",
    en: "mouse, mice",
    pt: "camundongo(s), rato(s)",
    category: "Connection - 3 - C",
  },
  {
    id: "e3j4b0zu",
    en: "rat",
    pt: "rato, ratazana",
    category: "Connection - 3 - C",
  },
  { id: "w5c2s8yf", en: "rain", pt: "chuva", category: "Connection - 3 - C" },
  {
    id: "n1t6v9pq",
    en: "sweetheart",
    pt: "querida(a), namoradinho(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "p4k3h7dl",
    en: "honey",
    pt: "mel, querido(a)",
    category: "Connection - 3 - C",
  },
  {
    id: "a9t4v7kp",
    en: "to choose",
    pt: "escolher",
    category: "Connection - 4 - A",
  },
  {
    id: "f2r8c6mj",
    en: "to fly",
    pt: "voar, viajar de avião",
    category: "Connection - 4 - A",
  },
  {
    id: "k5n1b9qt",
    en: "to plan",
    pt: "planejar",
    category: "Connection - 4 - A",
  },
  {
    id: "x0s7p3dl",
    en: "to decide",
    pt: "decidir",
    category: "Connection - 4 - A",
  },
  {
    id: "l4g2m8wh",
    en: "to book",
    pt: "fazer reserva",
    category: "Connection - 4 - A",
  },
  {
    id: "v9y5h1rx",
    en: "to carry",
    pt: "carregar",
    category: "Connection - 4 - A",
  },
  {
    id: "n6b0q8za",
    en: "to pack",
    pt: "fazer as malas, empacotar",
    category: "Connection - 4 - A",
  },
  {
    id: "p3k9j7eu",
    en: "to return (from/to)",
    pt: "retornar, devolver",
    category: "Connection - 4 - A",
  },
  {
    id: "t1m4d2wy",
    en: "to go sightseeing",
    pt: "visitar pontos turísticos",
    category: "Connection - 4 - A",
  },
  {
    id: "b7f5n3lk",
    en: "to go diving / to dive",
    pt: "mergulhar",
    category: "Connection - 4 - A",
  },
  {
    id: "e8x9r6cv",
    en: "to go surfing / to surf",
    pt: "surfar",
    category: "Connection - 4 - A",
  },
  {
    id: "s2q7y1zh",
    en: "to go sailing / to sail",
    pt: "velejar",
    category: "Connection - 4 - A",
  },
  { id: "j5u0k4pn", en: "world", pt: "mundo", category: "Connection - 4 - A" },
  {
    id: "m8a9c2gf",
    en: "reservation",
    pt: "reserva",
    category: "Connection - 4 - A",
  },
  {
    id: "g6w3d1bj",
    en: "ticket",
    pt: "passagem, ingresso, multa",
    category: "Connection - 4 - A",
  },
  { id: "r9h7x5tv", en: "flight", pt: "vôo", category: "Connection - 4 - A" },
  {
    id: "c4z8l0pq",
    en: "boarding pass",
    pt: "cartão de embarque",
    category: "Connection - 4 - A",
  },
  {
    id: "u2v5y9mw",
    en: "luggage, baggage",
    pt: "bagagem",
    category: "Connection - 4 - A",
  },
  {
    id: "d3s1j8hk",
    en: "suitcase",
    pt: "mala",
    category: "Connection - 4 - A",
  },
  {
    id: "z7f6n4eb",
    en: "briefcase",
    pt: "maleta, pasta",
    category: "Connection - 4 - A",
  },
  { id: "w5q2p9rx", en: "pocket", pt: "bolso", category: "Connection - 4 - A" },
  {
    id: "o9t1m7ay",
    en: "aisle",
    pt: "corredor",
    category: "Connection - 4 - A",
  },
  {
    id: "h8b3v5nl",
    en: "airline",
    pt: "companhia aérea",
    category: "Connection - 4 - A",
  },
  {
    id: "y0d4r6qw",
    en: "surfboard",
    pt: "prancha de surfe",
    category: "Connection - 4 - A",
  },
  {
    id: "a2k9c8gp",
    en: "passport",
    pt: "passaporte",
    category: "Connection - 4 - A",
  },
  {
    id: "f7x3l1je",
    en: "ID, identification",
    pt: "identidade",
    category: "Connection - 4 - A",
  },
  { id: "l6m8y2ct", en: "visa", pt: "visto", category: "Connection - 4 - A" },
  {
    id: "p5r9s0dw",
    en: "consulate",
    pt: "consulado",
    category: "Connection - 4 - A",
  },
  { id: "k3n4v7qh", en: "gate", pt: "portão", category: "Connection - 4 - A" },
  {
    id: "x1t5b9fz",
    en: "around",
    pt: "ao redor",
    category: "Connection - 4 - A",
  },
  { id: "e4y2m6vw", en: "both", pt: "ambos", category: "Connection - 4 - A" },
  {
    id: "c9p8q3na",
    en: "either, either of",
    pt: "qualquer",
    category: "Connection - 4 - A",
  },
  {
    id: "v0j7g5tx",
    en: "neither, neither of",
    pt: "nenhuma",
    category: "Connection - 4 - A",
  },
  {
    id: "b8d6h4lu",
    en: "either...or",
    pt: "ou...ou",
    category: "Connection - 4 - A",
  },
  {
    id: "n2s9y1mw",
    en: "neither...nor",
    pt: "nem...nem",
    category: "Connection - 4 - A",
  },
  {
    id: "r4k3a9hf",
    en: "it doesn't matter",
    pt: "não importa",
    category: "Connection - 4 - A",
  },
  {
    id: "m6v8p0tc",
    en: "here you are / here you go",
    pt: "aqui está",
    category: "Connection - 4 - A",
  },
  {
    id: "t9f5w7el",
    en: "to check in",
    pt: "fazer o check in",
    category: "Connection - 4 - A",
  },
  {
    id: "u1b3q8yn",
    en: "to check",
    pt: "despachar a bagagem",
    category: "Connection - 4 - A",
  },
  {
    id: "g7r4x2zp",
    en: "to carry-on",
    pt: "levar como bagagem de mão, continuar",
    category: "Connection - 4 - A",
  },
  {
    id: "y5m0h6dj",
    en: "pacifier",
    pt: "chupeta",
    category: "Connection - 4 - A",
  },
  {
    id: "w8n9v2ka",
    en: "diaper",
    pt: "fralda",
    category: "Connection - 4 - A",
  },
  {
    id: "a3t1s7qx",
    en: "bottle",
    pt: "mamadeira",
    category: "Connection - 4 - A",
  },
  {
    id: "k9e5p4lw",
    en: "to go camping / to camp out",
    pt: "acampar",
    category: "Connection - 4 - A",
  },
  {
    id: "x2d6g8ry",
    en: "to go bowling / to bowl",
    pt: "jogar boliche",
    category: "Connection - 4 - A",
  },
  {
    id: "z0j7n5mf",
    en: "to go skiing / to ski",
    pt: "esquiar",
    category: "Connection - 4 - A",
  },
  {
    id: "h1p9b3cv",
    en: "to go hiking / to hike",
    pt: "caminhar",
    category: "Connection - 4 - A",
  },
  {
    id: "l4s8f0tn",
    en: "to go snorkeling / to snorkel",
    pt: "mergulhar com snorkel",
    category: "Connection - 4 - A",
  },
  {
    id: "q5r2w7ae",
    en: "to go skydiving / to skydive",
    pt: "pular de paraquedas",
    category: "Connection - 4 - A",
  },
  {
    id: "a9k4r2mv",
    en: "to be named after",
    pt: "receber o mesmo nome de",
    category: "Connection - 4 - B",
  },
  {
    id: "f3p8n7cq",
    en: "to look like",
    pt: "parecer com",
    category: "Connection - 4 - B",
  },
  {
    id: "k1s6b5jt",
    en: "to take after",
    pt: "'puxar' a",
    category: "Connection - 4 - B",
  },
  {
    id: "x2w9d3gl",
    en: "to describe",
    pt: "descrever",
    category: "Connection - 4 - B",
  },
  {
    id: "l7g8c1wh",
    en: "features",
    pt: "características",
    category: "Connection - 4 - B",
  },
  {
    id: "v0y5m9rx",
    en: "appearance, look",
    pt: "aparência",
    category: "Connection - 4 - B",
  },
  {
    id: "n4b2q6za",
    en: "complexion",
    pt: "aspecto, tez (cor da pele)",
    category: "Connection - 4 - B",
  },
  { id: "p9k3j7eu", en: "face", pt: "rosto", category: "Connection - 4 - B" },
  { id: "t6m5d2wy", en: "nose", pt: "nariz", category: "Connection - 4 - B" },
  { id: "b1f9n8lk", en: "eyes", pt: "olhos", category: "Connection - 4 - B" },
  { id: "e2x7r6cv", en: "skin", pt: "pele", category: "Connection - 4 - B" },
  { id: "s8q4y1zh", en: "hair", pt: "cabelo", category: "Connection - 4 - B" },
  { id: "j0u9k4pn", en: "tall", pt: "alto(a)", category: "Connection - 4 - B" },
  {
    id: "m3a6c2gf",
    en: "short",
    pt: "baixo(a)",
    category: "Connection - 4 - B",
  },
  {
    id: "g5w1d9bj",
    en: "average height",
    pt: "altura mediana",
    category: "Connection - 4 - B",
  },
  {
    id: "r8h7x5tv",
    en: "dark haired",
    pt: "de cabelos escuros",
    category: "Connection - 4 - B",
  },
  {
    id: "c6z3l0pq",
    en: "red haired",
    pt: "de cabelos ruivos",
    category: "Connection - 4 - B",
  },
  {
    id: "u2v5y9mw",
    en: "blond",
    pt: "de cabelos louros",
    category: "Connection - 4 - B",
  },
  {
    id: "d3s1j8hk",
    en: "curly hair",
    pt: "cabelo enrolado",
    category: "Connection - 4 - B",
  },
  {
    id: "z7f6n4eb",
    en: "wavy hair",
    pt: "cabelo ondulado",
    category: "Connection - 4 - B",
  },
  {
    id: "w5q2p9rx",
    en: "straight hair",
    pt: "cabelo liso",
    category: "Connection - 4 - B",
  },
  { id: "o9t1m7ay", en: "bald", pt: "careca", category: "Connection - 4 - B" },
  {
    id: "h8b3v5nl",
    en: "fat, overweight",
    pt: "gordo(a)",
    category: "Connection - 4 - B",
  },
  {
    id: "y0d4r6qw",
    en: "thin, slim",
    pt: "magro(a)",
    category: "Connection - 4 - B",
  },
  {
    id: "a2k9c8gp",
    en: "skinny",
    pt: "magro(a), magrinho(a)",
    category: "Connection - 4 - B",
  },
  {
    id: "f7x3l1je",
    en: "well-built",
    pt: "grande e forte",
    category: "Connection - 4 - B",
  },
  {
    id: "l6m8y2ct",
    en: "muscular, buffed",
    pt: "musculoso(a)",
    category: "Connection - 4 - B",
  },
  { id: "p5r9s0dw", en: "fit", pt: "em forma", category: "Connection - 4 - B" },
  { id: "k3n4v7qh", en: "beard", pt: "barba", category: "Connection - 4 - B" },
  {
    id: "x1t5b9fz",
    en: "mustache",
    pt: "bigode",
    category: "Connection - 4 - B",
  },
  {
    id: "e4y2m6vw",
    en: "goatee",
    pt: "cavanhaque",
    category: "Connection - 4 - B",
  },
  {
    id: "c9p8q3na",
    en: "freckles, freckled",
    pt: "(com) sardas",
    category: "Connection - 4 - B",
  },
  {
    id: "v0j7g5tx",
    en: "wrinkles, wrinkled",
    pt: "(com) rugas",
    category: "Connection - 4 - B",
  },
  {
    id: "b8d6h4lu",
    en: "middle-aged",
    pt: "de meia-idade",
    category: "Connection - 4 - B",
  },
  {
    id: "n2s9y1mw",
    en: "twins",
    pt: "gêmeos(as)",
    category: "Connection - 4 - B",
  },
  {
    id: "r4k3a9hf",
    en: "definitely",
    pt: "com certeza",
    category: "Connection - 4 - B",
  },
  {
    id: "m6v8p0tc",
    en: "a redhead",
    pt: "uma ruiva, um ruivo",
    category: "Connection - 4 - B",
  },
  {
    id: "t9f5w7el",
    en: "a brunette, brunet",
    pt: "uma morena, um moreno",
    category: "Connection - 4 - B",
  },
  {
    id: "u1b3q8yn",
    en: "a blonde, blond",
    pt: "uma loira, um louro",
    category: "Connection - 4 - B",
  },
  {
    id: "g7r4x2zp",
    en: "gray hair",
    pt: "cabelo branco, grisalho",
    category: "Connection - 4 - B",
  },
  {
    id: "y5m0h6dj",
    en: "facial hair",
    pt: "pêlos faciais",
    category: "Connection - 4 - B",
  },
  {
    id: "w8n9v2ka",
    en: "average",
    pt: "média",
    category: "Connection - 4 - B",
  },
  {
    id: "a3t1s7qx",
    en: "fair-skinned",
    pt: "de pele bem clara",
    category: "Connection - 4 - B",
  },
  {
    id: "k9e5p4lw",
    en: "tanned",
    pt: "bronzeado",
    category: "Connection - 4 - B",
  },
  { id: "x2d6g8ry", en: "pale", pt: "pálido", category: "Connection - 4 - B" },
  {
    id: "z0j7n5mf",
    en: "to dye, to color hair",
    pt: "colorir, pintar os cabelos",
    category: "Connection - 4 - B",
  },
  {
    id: "h1p9b3cv",
    en: "to be in (his) 20's",
    pt: "ter entre 20 e 29 anos",
    category: "Connection - 4 - B",
  },
  {
    id: "l4s8f0tn",
    en: "to be in (her) late 30's",
    pt: "ter 30 e tal (anos)",
    category: "Connection - 4 - B",
  },
  {
    id: "q5r2w7ae",
    en: "to be in (my) early 40's",
    pt: "ter 40 e poucos anos",
    category: "Connection - 4 - B",
  },
  {
    id: "c4a1x9pm",
    en: "to seem, to look",
    pt: "parecer, dar a impressão",
    category: "Connection - 4 - C",
  },
  {
    id: "u7k2b5rq",
    en: "to sound",
    pt: "soar, parecer",
    category: "Connection - 4 - C",
  },
  {
    id: "m9f3t1vz",
    en: "to behave, to act",
    pt: "comportar-se",
    category: "Connection - 4 - C",
  },
  {
    id: "p6n8j2yd",
    en: "to dream (of/about)",
    pt: "sonhar(com)",
    category: "Connection - 4 - C",
  },
  {
    id: "r1q7e4ks",
    en: "to keep, to continue",
    pt: "continuar",
    category: "Connection - 4 - C",
  },
  {
    id: "a8d5w2hl",
    en: "to begin",
    pt: "começar",
    category: "Connection - 4 - C",
  },
  {
    id: "x2v6g9cj",
    en: "to fool",
    pt: "enganar",
    category: "Connection - 4 - C",
  },
  {
    id: "s0y3n7we",
    en: "such, such a/an",
    pt: "tão",
    category: "Connection - 4 - C",
  },
  {
    id: "k5h9p1tu",
    en: "fool, foolish",
    pt: "bobo, tolo, insensato",
    category: "Connection - 4 - C",
  },
  {
    id: "b3l4c8ra",
    en: "lazy",
    pt: "preguiçoso",
    category: "Connection - 4 - C",
  },
  {
    id: "j9m2f6qo",
    en: "scared",
    pt: "assustado, com medo",
    category: "Connection - 4 - C",
  },
  {
    id: "y4t1z7nx",
    en: "easygoing",
    pt: "fácil de lidar, descontraído",
    category: "Connection - 4 - C",
  },
  {
    id: "e7p0k5md",
    en: "annoying",
    pt: "irritante, chato",
    category: "Connection - 4 - C",
  },
  {
    id: "q6w3r8ib",
    en: "boring",
    pt: "entediante, chato",
    category: "Connection - 4 - C",
  },
  {
    id: "n5c2a9uv",
    en: "selfish",
    pt: "egoísta",
    category: "Connection - 4 - C",
  },
  {
    id: "t8s4h1pk",
    en: "stuck-up, snobbish",
    pt: "metido, esnobe",
    category: "Connection - 4 - C",
  },
  {
    id: "g0d7v2xe",
    en: "talkative, chatty",
    pt: "falante",
    category: "Connection - 4 - C",
  },
  {
    id: "z1r6m3wf",
    en: "stubborn",
    pt: "teimoso",
    category: "Connection - 4 - C",
  },

  { id: "h2a9k5ql", en: "shy", pt: "tímido", category: "Connection - 4 - C" },
  {
    id: "f3o7n1cb",
    en: "outgoing",
    pt: "extrovertido",
    category: "Connection - 4 - C",
  },
  { id: "v6e4p8rt", en: "silly", pt: "bobo", category: "Connection - 4 - C" },
  {
    id: "d5u0y2jn",
    en: "mean",
    pt: "mau, malvado",
    category: "Connection - 4 - C",
  },
  {
    id: "w7i3l6ga",
    en: "moody",
    pt: "mal-humorado, temperamental",
    category: "Connection - 4 - C",
  },
  {
    id: "c9x1s4mp",
    en: "nasty",
    pt: "desagradável, maldoso",
    category: "Connection - 4 - C",
  },
  {
    id: "o4b8q2yz",
    en: "neat",
    pt: "organizado, arrumado",
    category: "Connection - 4 - C",
  },
  {
    id: "l0g5e7td",
    en: "nice",
    pt: "agradável, simpático, bom",
    category: "Connection - 4 - C",
  },
  { id: "u3m9k6re", en: "loyal", pt: "leal", category: "Connection - 4 - C" },
  {
    id: "p2n7j5cv",
    en: "tough",
    pt: "resistente, duro, difícil",
    category: "Connection - 4 - C",
  },
  {
    id: "i8y0a3hs",
    en: "understanding",
    pt: "compreensivo",
    category: "Connection - 4 - C",
  },
  {
    id: "r7q4f9bn",
    en: "proud",
    pt: "orgulhoso",
    category: "Connection - 4 - C",
  },
  {
    id: "x5t2w8ko",
    en: "smart",
    pt: "inteligente, esperto",
    category: "Connection - 4 - C",
  },
  {
    id: "a6c1d7vz",
    en: "naughty",
    pt: "desobediente, levado",
    category: "Connection - 4 - C",
  },
  {
    id: "k4h8p0uw",
    en: "dumb, stupid",
    pt: "burro",
    category: "Connection - 4 - C",
  },
  {
    id: "s9e3m6ji",
    en: "coward, cowardly",
    pt: "covarde, medroso",
    category: "Connection - 4 - C",
  },
  {
    id: "b1l5v8qa",
    en: "kind / unkind",
    pt: "bondoso/amável, cruel/indelicado",
    category: "Connection - 4 - C",
  },
  {
    id: "y2z6n4tx",
    en: "polite / impolite",
    pt: "educado / mal-educado",
    category: "Connection - 4 - C",
  },

  {
    id: "m1a4r7ce",
    en: "ambitious",
    pt: "ambicioso",
    category: "Connection - 4 - C",
  },
  {
    id: "q8p2k5bd",
    en: "courageous, brave",
    pt: "corajoso",
    category: "Connection - 4 - C",
  },
  {
    id: "j6f9t3ow",
    en: "honest",
    pt: "honesto",
    category: "Connection - 4 - C",
  },
  {
    id: "e4s7c0lu",
    en: "sarcastic",
    pt: "sarcástico",
    category: "Connection - 4 - C",
  },
  {
    id: "n3v8y1ip",
    en: "quiet",
    pt: "quieto, silencioso",
    category: "Connection - 4 - C",
  },
  {
    id: "t9g6h2rm",
    en: "intelligent",
    pt: "inteligente",
    category: "Connection - 4 - C",
  },
  { id: "z0x5w8qa", en: "idiot", pt: "idiota", category: "Connection - 4 - C" },

  {
    id: "h3k7p1dv",
    en: "patient / impatient",
    pt: "paciente / impaciente",
    category: "Connection - 4 - C",
  },
  {
    id: "v5e9m2ts",
    en: "mature / immature",
    pt: "maduro, imaturo",
    category: "Connection - 4 - C",
  },
  {
    id: "d2u6y4gb",
    en: "rude",
    pt: "rude, grosseiro",
    category: "Connection - 4 - C",
  },
  {
    id: "w8i0l3ca",
    en: "childish",
    pt: "infantil",
    category: "Connection - 4 - C",
  },
  {
    id: "c7x1s5ne",
    en: "friendly",
    pt: "amigável",
    category: "Connection - 4 - C",
  },
  {
    id: "o9b4q6yj",
    en: "helpful",
    pt: "prestativo, útil",
    category: "Connection - 4 - C",
  },
  {
    id: "l6g2e7kp",
    en: "loving",
    pt: "amoroso, carinhoso",
    category: "Connection - 4 - C",
  },
  {
    id: "d4k1a9zx",
    en: "coastline",
    pt: "costa",
    category: "Connection - 4 - D",
  },
  { id: "m7q3v2ln", en: "skies", pt: "céus", category: "Connection - 4 - D" },
  {
    id: "p9t6w1rb",
    en: "bordering",
    pt: "fazendo borda com",
    category: "Connection - 4 - D",
  },
  {
    id: "x2f8c5ey",
    en: "plenty",
    pt: "bastante",
    category: "Connection - 4 - D",
  },
  { id: "u1n7s4jp", en: "reefs", pt: "corais", category: "Connection - 4 - D" },
  {
    id: "k6b0r3ha",
    en: "aquamarine",
    pt: "água-marinha",
    category: "Connection - 4 - D",
  },
  {
    id: "g8z2q1md",
    en: "kayaking",
    pt: "andar de caiaque",
    category: "Connection - 4 - D",
  },
  {
    id: "v5h9l0tc",
    en: "paragliding",
    pt: "parapente",
    category: "Connection - 4 - D",
  },
  { id: "a3s7d6wu", en: "wide", pt: "amplos", category: "Connection - 4 - D" },
  {
    id: "r0y4e8kv",
    en: "hot air balloon",
    pt: "balão de ar quente",
    category: "Connection - 4 - D",
  },

  { id: "n2c6p9fj", en: "seek", pt: "procura", category: "Connection - 4 - D" },
  { id: "q7w1m3az", en: "than", pt: "que", category: "Connection - 4 - D" },
  { id: "e6t5b2xo", en: "ruins", pt: "ruínas", category: "Connection - 4 - D" },
  {
    id: "y4k8h1pr",
    en: "preserved",
    pt: "preservados",
    category: "Connection - 4 - D",
  },
  {
    id: "j1l9u5sd",
    en: "converted",
    pt: "convertidos",
    category: "Connection - 4 - D",
  },
  {
    id: "z5a0x3ng",
    en: "private",
    pt: "particulares",
    category: "Connection - 4 - D",
  },
  {
    id: "b8m2r6qh",
    en: "government",
    pt: "governo",
    category: "Connection - 4 - D",
  },
  {
    id: "t3p4c7iv",
    en: "have become",
    pt: "tornaram-se",
    category: "Connection - 4 - D",
  },
  {
    id: "h9f6e1uy",
    en: "models",
    pt: "modelos",
    category: "Connection - 4 - D",
  },
  {
    id: "c1s8d5kw",
    en: "have been used",
    pt: "foram usados",
    category: "Connection - 4 - D",
  },
  {
    id: "l0r7v2pb",
    en: "settings",
    pt: "cenários",
    category: "Connection - 4 - D",
  },
  { id: "o6g3a9qe", en: "epic", pt: "épico", category: "Connection - 4 - D" },
  {
    id: "w2x5n8jt",
    en: "built",
    pt: "construído",
    category: "Connection - 4 - D",
  },
  {
    id: "f7u1k4am",
    en: "Moorish",
    pt: "mouro",
    category: "Connection - 4 - D",
  },
  {
    id: "s9d0y3cl",
    en: "plains",
    pt: "planície",
    category: "Connection - 4 - D",
  },

  { id: "i4v8b2rx", en: "whether", pt: "quer", category: "Connection - 4 - D" },
  {
    id: "p6e9t1oy",
    en: "bohemian",
    pt: "boêmio",
    category: "Connection - 4 - D",
  },
  { id: "m3k7q5ua", en: "gem", pt: "jóia", category: "Connection - 4 - D" },
  {
    id: "a9h2f6zw",
    en: "taking in the sights",
    pt: "aproveitando a vista",
    category: "Connection - 4 - D",
  },
  { id: "r5n0c8jb", en: "tip", pt: "dica", category: "Connection - 4 - D" },
  {
    id: "g1y4w7lk",
    en: "in advance",
    pt: "com antecedência",
    category: "Connection - 4 - D",
  },
  {
    id: "x8t2p6sd",
    en: "bypass",
    pt: "evitar",
    category: "Connection - 4 - D",
  },
  {
    id: "k0m9e3qh",
    en: "crowds",
    pt: "multidões",
    category: "Connection - 4 - D",
  },
  {
    id: "u7b5v1fa",
    en: "tour guide",
    pt: "guia turístico",
    category: "Connection - 4 - D",
  },
  {
    id: "d2c6z9pn",
    en: "point out",
    pt: "apontar",
    category: "Connection - 4 - D",
  },
  { id: "y6o1r4we", en: "pieces", pt: "peças", category: "Connection - 4 - D" },
  {
    id: "j3l8q0tm",
    en: "Cathedral",
    pt: "catedral",
    category: "Connection - 4 - D",
  },
  {
    id: "v9a2k5xh",
    en: "finest",
    pt: "melhor e mais elegante",
    category: "Connection - 4 - D",
  },
  {
    id: "b4p7s1ug",
    en: "Gothic",
    pt: "gótico",
    category: "Connection - 4 - D",
  },
  {
    id: "o1n6e3rv",
    en: "architecture",
    pt: "arquitetura",
    category: "Connection - 4 - D",
  },
  {
    id: "h8f0t2cy",
    en: "Revolutionary",
    pt: "revolucionária",
    category: "Connection - 4 - D",
  },
  {
    id: "q5w3m9kd",
    en: "come alive",
    pt: "que ganha vida",
    category: "Connection - 4 - D",
  },
  {
    id: "a1x9p4km",
    en: "to fix, to repair",
    pt: "consertar",
    category: "Connection - 5 - A",
  },
  {
    id: "b7q2v6ln",
    en: "to build",
    pt: "construir",
    category: "Connection - 5 - A",
  },
  {
    id: "c3t8w1rb",
    en: "to work",
    pt: "funcionar",
    category: "Connection - 5 - A",
  },
  {
    id: "d6f5c8ey",
    en: "to put together, to assemble",
    pt: "montar",
    category: "Connection - 5 - A",
  },
  {
    id: "e2n7s4jp",
    en: "to clean up",
    pt: "organizar e limpar",
    category: "Connection - 5 - A",
  },
  {
    id: "f9k0r3ha",
    en: "to be made out of",
    pt: "ser feito de",
    category: "Connection - 5 - A",
  },
  {
    id: "g8z1q2md",
    en: "plumber",
    pt: "bombeiro hidráulico",
    category: "Connection - 5 - A",
  },
  {
    id: "h5v9l0tc",
    en: "factory",
    pt: "fábrica",
    category: "Connection - 5 - A",
  },
  { id: "i3s7d6wu", en: "wood", pt: "madeira", category: "Connection - 5 - A" },
  {
    id: "j0y4e8kv",
    en: "part",
    pt: "peças, partes",
    category: "Connection - 5 - A",
  },
  {
    id: "k6c2p9fj",
    en: "piece",
    pt: "peça, pedaço",
    category: "Connection - 5 - A",
  },
  {
    id: "l1w3m7az",
    en: "tools",
    pt: "ferramentas",
    category: "Connection - 5 - A",
  },
  {
    id: "m4t5b2xo",
    en: "toolbox",
    pt: "caixa de ferramentas",
    category: "Connection - 5 - A",
  },
  {
    id: "n9k8h1pr",
    en: "hammer",
    pt: "martelo",
    category: "Connection - 5 - A",
  },
  { id: "o2l5u5sd", en: "nail", pt: "prego", category: "Connection - 5 - A" },
  {
    id: "p7a0x3ng",
    en: "pliers",
    pt: "alicate",
    category: "Connection - 5 - A",
  },
  {
    id: "q5m2r6qh",
    en: "wrench",
    pt: "chave inglesa",
    category: "Connection - 5 - A",
  },
  {
    id: "r8p4c7iv",
    en: "screwdriver",
    pt: "chave de fenda",
    category: "Connection - 5 - A",
  },

  {
    id: "s6f6e1uy",
    en: "screws",
    pt: "parafusos",
    category: "Connection - 5 - A",
  },
  {
    id: "t1s8d5kw",
    en: "nuts and bolts",
    pt: "porcas e parafusos",
    category: "Connection - 5 - A",
  },
  {
    id: "u0r7v2pb",
    en: "scissors",
    pt: "tesoura",
    category: "Connection - 5 - A",
  },
  { id: "v6g3a9qe", en: "saw", pt: "serra", category: "Connection - 5 - A" },
  {
    id: "w2x5n8jt",
    en: "drill",
    pt: "furadeira",
    category: "Connection - 5 - A",
  },
  {
    id: "x7u1k4am",
    en: "goggles",
    pt: "óculos de proteção, natação, mergulho",
    category: "Connection - 5 - A",
  },
  {
    id: "y9d0y3cl",
    en: "flashlight",
    pt: "lanterna",
    category: "Connection - 5 - A",
  },
  {
    id: "z4v8b2rx",
    en: "machine",
    pt: "máquina",
    category: "Connection - 5 - A",
  },
  {
    id: "a0e9t1oy",
    en: "upside down",
    pt: "de cabeça pra baixo",
    category: "Connection - 5 - A",
  },
  {
    id: "b3k7q5ua",
    en: "instructions",
    pt: "instruções",
    category: "Connection - 5 - A",
  },
  {
    id: "c9h2f6zw",
    en: "bench",
    pt: "banco(de jardim de praça)",
    category: "Connection - 5 - A",
  },
  {
    id: "d5n0c8jb",
    en: "way",
    pt: "caminho, maneira",
    category: "Connection - 5 - A",
  },
  { id: "e1y4w7lk", en: "mess", pt: "bagunça", category: "Connection - 5 - A" },
  {
    id: "f8t2p6sd",
    en: "safety",
    pt: "segurança",
    category: "Connection - 5 - A",
  },
  {
    id: "g0m9e3qh",
    en: "garage",
    pt: "garagem",
    category: "Connection - 5 - A",
  },
  {
    id: "h7b5v1fa",
    en: "grumpy",
    pt: "mal-humorado, rabugento",
    category: "Connection - 5 - A",
  },
  {
    id: "i2c6z9pn",
    en: "practical",
    pt: "prático(a)",
    category: "Connection - 5 - A",
  },
  {
    id: "j6o1r4we",
    en: "optimistic",
    pt: "otimista",
    category: "Connection - 5 - A",
  },

  {
    id: "k3l8q0tm",
    en: "modest",
    pt: "modesto(a)",
    category: "Connection - 5 - A",
  },
  {
    id: "l9a2k5xh",
    en: "messy",
    pt: "bagunçado(a)",
    category: "Connection - 5 - A",
  },
  {
    id: "m4p7s1ug",
    en: "confident",
    pt: "confiante",
    category: "Connection - 5 - A",
  },
  {
    id: "n1n6e3rv",
    en: "instruction manual",
    pt: "manual de instruções",
    category: "Connection - 5 - A",
  },
  {
    id: "o8f0t2cy",
    en: "washing machine, washer",
    pt: "máquina de lavar, lavadora de roupas",
    category: "Connection - 5 - A",
  },
  {
    id: "p5w3m9kd",
    en: "dryer",
    pt: "secadora de roupas",
    category: "Connection - 5 - A",
  },
  {
    id: "q2h7p1dv",
    en: "laundry room",
    pt: "lavanderia",
    category: "Connection - 5 - A",
  },
  {
    id: "f1x9a2lm",
    en: "to win",
    pt: "vencer",
    category: "Connection - 5 - B",
  },
  {
    id: "k7p3v6rd",
    en: "to beat, to defeat",
    pt: "derrotar",
    category: "Connection - 5 - B",
  },
  {
    id: "a9t4m1qc",
    en: "to train",
    pt: "treinar",
    category: "Connection - 5 - B",
  },
  {
    id: "u6b2y8we",
    en: "to practice",
    pt: "praticar",
    category: "Connection - 5 - B",
  },
  {
    id: "r3n7k5zo",
    en: "to race",
    pt: "correr, competir",
    category: "Connection - 5 - B",
  },
  {
    id: "d8h1s4vp",
    en: "to score",
    pt: "marcar pontos",
    category: "Connection - 5 - B",
  },
  {
    id: "m2c9e7jt",
    en: "to pretend",
    pt: "fingir",
    category: "Connection - 5 - B",
  },
  {
    id: "q5w0l3ry",
    en: "to intend",
    pt: "pretender",
    category: "Connection - 5 - B",
  },
  {
    id: "x4g6b1un",
    en: "to dress up",
    pt: "vestir-se elegantemente ou à fantasia",
    category: "Connection - 5 - B",
  },
  { id: "z7v2p5ka", en: "team", pt: "time", category: "Connection - 5 - B" },
  { id: "e3j8r0cf", en: "leader", pt: "líder", category: "Connection - 5 - B" },
  {
    id: "t6s1n4mw",
    en: "player",
    pt: "jogador",
    category: "Connection - 5 - B",
  },
  {
    id: "b0k9q7dx",
    en: "race car driver",
    pt: "piloto de corridas",
    category: "Connection - 5 - B",
  },
  {
    id: "y1p5h8az",
    en: "runner, racer",
    pt: "corredor",
    category: "Connection - 5 - B",
  },
  {
    id: "c4m2t6vg",
    en: "competition",
    pt: "competição",
    category: "Connection - 5 - B",
  },
  {
    id: "n8l3f1qp",
    en: "champion",
    pt: "campeão",
    category: "Connection - 5 - B",
  },
  {
    id: "g2d7w9he",
    en: "coach",
    pt: "técnico, treinador",
    category: "Connection - 5 - B",
  },
  {
    id: "p9a1x3sk",
    en: "championship",
    pt: "campeonato",
    category: "Connection - 5 - B",
  },

  {
    id: "h5u0c2bn",
    en: "marathon",
    pt: "maratona",
    category: "Connection - 5 - B",
  },
  {
    id: "v6r3e9jy",
    en: "race",
    pt: "corrida, raça",
    category: "Connection - 5 - B",
  },
  {
    id: "j4o8m6ta",
    en: "match",
    pt: "partida",
    category: "Connection - 5 - B",
  },
  {
    id: "s7i2k5pl",
    en: "points",
    pt: "pontos",
    category: "Connection - 5 - B",
  },
  {
    id: "w3f9z1qu",
    en: "national",
    pt: "nacional",
    category: "Connection - 5 - B",
  },
  {
    id: "l0y6d4re",
    en: "league",
    pt: "liga, campeonato",
    category: "Connection - 5 - B",
  },
  {
    id: "o2t5b8kc",
    en: "distance",
    pt: "distância",
    category: "Connection - 5 - B",
  },
  {
    id: "a6n1g7mx",
    en: "salary",
    pt: "salário",
    category: "Connection - 5 - B",
  },
  {
    id: "f9q4p0dz",
    en: "that's why",
    pt: "é por isso que",
    category: "Connection - 5 - B",
  },
  {
    id: "k1x8e2wg",
    en: "nowadays",
    pt: "hoje em dia, atualmente",
    category: "Connection - 5 - B",
  },
  {
    id: "r5b7u9co",
    en: "actually",
    pt: "na verdade, para dizer a verdade",
    category: "Connection - 5 - B",
  },
  { id: "d2m6h3iv", en: "badly", pt: "mal", category: "Connection - 5 - B" },
  { id: "y8c1a4tn", en: "court", pt: "quadra", category: "Connection - 5 - B" },
  { id: "u0s9l5pe", en: "field", pt: "campo", category: "Connection - 5 - B" },
  {
    id: "x3g2k7qa",
    en: "track",
    pt: "pista(de correr), trilho(de trem)",
    category: "Connection - 5 - B",
  },
  {
    id: "z6v5r1mh",
    en: "track and field",
    pt: "atletismo",
    category: "Connection - 5 - B",
  },
  {
    id: "e1j0w8fb",
    en: "someday",
    pt: "um dia, algum dia",
    category: "Connection - 5 - B",
  },
  { id: "t4i9n6ku", en: "place", pt: "lugar", category: "Connection - 5 - B" },

  {
    id: "m7p2q5gh",
    en: "hide-and-seek",
    pt: "esconde-esconde",
    category: "Connection - 5 - B",
  },
  {
    id: "c9a4e1rx",
    en: "tag",
    pt: "pega-pega",
    category: "Connection - 5 - B",
  },
  {
    id: "b8n3y6zw",
    en: "dodgeball",
    pt: "queimada",
    category: "Connection - 5 - B",
  },
  {
    id: "g2k7m0vt",
    en: "capture the flag",
    pt: "pique-bandeira, captura à bandeira",
    category: "Connection - 5 - B",
  },
  {
    id: "p5s1l8do",
    en: "to play pretend",
    pt: "brincar de faz de contas",
    category: "Connection - 5 - B",
  },
  {
    id: "h0f6u3qc",
    en: "to play dress up",
    pt: "brincar de se fantasiar",
    category: "Connection - 5 - B",
  },
  {
    id: "n1w4x9ab",
    en: "cops and robbers",
    pt: "polícia e ladrão",
    category: "Connection - 5 - B",
  },
  {
    id: "c5c-001",
    en: "to attend",
    pt: "assistir, participar",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-002",
    en: "to improve",
    pt: "melhorar",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-003",
    en: "to complain(about)",
    pt: "reclamar",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-004",
    en: "to quit",
    pt: "parar, desistir",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-005",
    en: "to skip",
    pt: "pular, 'matar' aulas",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-006",
    en: "to realize",
    pt: "perceber, se dar conta",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-007",
    en: "to copy",
    pt: "copiar",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-008",
    en: "to create",
    pt: "criar",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-009",
    en: "to repeat",
    pt: "repetir",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-010",
    en: "to correct",
    pt: "corrigir",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-011",
    en: "to pay attention(to)",
    pt: "prestar atenção",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-012",
    en: "to come true",
    pt: "tornar-se realidade, realizar-se",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-013",
    en: "lecture",
    pt: "palestra",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-014",
    en: "seminar",
    pt: "seminário",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-015",
    en: "performance",
    pt: "desempenho",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-016",
    en: "planet",
    pt: "planeta",
    category: "Connection - 5 - C",
  },
  { id: "c5c-017", en: "Earth", pt: "Terra", category: "Connection - 5 - C" },
  {
    id: "c5c-018",
    en: "elevator",
    pt: "elevador",
    category: "Connection - 5 - C",
  },

  {
    id: "c5c-019",
    en: "escalator",
    pt: "escada rolante",
    category: "Connection - 5 - C",
  },
  { id: "c5c-020", en: "mistake", pt: "erro", category: "Connection - 5 - C" },
  {
    id: "c5c-021",
    en: "sentence",
    pt: "frase, sentença",
    category: "Connection - 5 - C",
  },
  { id: "c5c-022", en: "stuff", pt: "coisas", category: "Connection - 5 - C" },
  {
    id: "c5c-023",
    en: "assignment",
    pt: "tarefa, trabalho",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-024",
    en: "during",
    pt: "durante",
    category: "Connection - 5 - C",
  },
  { id: "c5c-025", en: "close", pt: "perto", category: "Connection - 5 - C" },
  {
    id: "c5c-026",
    en: "bright",
    pt: "brilhoso, inteligente",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-027",
    en: "necessary/unnecessary",
    pt: "necessário, desnecessário",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-028",
    en: "what's going on",
    pt: "o que está acontecendo",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-029",
    en: "by the way",
    pt: "por falar nisso, a propósito",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-030",
    en: "on (my) way",
    pt: "no (meu) caminho, à caminho",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-031",
    en: "suddenly, all of a sudden",
    pt: "de repente",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-032",
    en: "after all",
    pt: "afinal, no final das contas",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-033",
    en: "just in case",
    pt: "no caso de",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-034",
    en: "now and then",
    pt: "de vez em quando",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-035",
    en: "at least",
    pt: "ao menos",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-036",
    en: "whole",
    pt: "inteiro(a), inteiros(as)",
    category: "Connection - 5 - C",
  },

  { id: "c5c-037", en: "Mars", pt: "Marte", category: "Connection - 5 - C" },
  { id: "c5c-038", en: "Venus", pt: "Vênus", category: "Connection - 5 - C" },
  {
    id: "c5c-039",
    en: "creative",
    pt: "criativo(a)",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-040",
    en: "complaint",
    pt: "reclamação",
    category: "Connection - 5 - C",
  },
  {
    id: "c5c-041",
    en: "original",
    pt: "original",
    category: "Connection - 5 - C",
  },
  { id: "c5c-042", en: "copy", pt: "cópia", category: "Connection - 5 - C" },
  { id: "c5c-043", en: "normal", pt: "normal", category: "Connection - 5 - C" },
  {
    id: "d5d-001",
    en: "widely",
    pt: "amplamente",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-002",
    en: "regarded",
    pt: "considerado",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-003",
    en: "leading",
    pt: "principal",
    category: "Connection - 5 - D",
  },
  { id: "d5d-004", en: "wheel", pt: "volante", category: "Connection - 5 - D" },
  {
    id: "d5d-005",
    en: "following",
    pt: "seguindo",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-006",
    en: "joined",
    pt: "juntou-se",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-007",
    en: "all but one",
    pt: "todos menos um",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-008",
    en: "has often been voted",
    pt: "tem sido votado frequentemente",
    category: "Connection - 5 - D",
  },
  { id: "d5d-009", en: "weather", pt: "clima", category: "Connection - 5 - D" },
  {
    id: "d5d-010",
    en: "succumbing",
    pt: "sucumbindo",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-011",
    en: "fatal injuries",
    pt: "ferimentos fatais",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-012",
    en: "sustained",
    pt: "sofrido",
    category: "Connection - 5 - D",
  },
  { id: "d5d-013", en: "death", pt: "morte", category: "Connection - 5 - D" },
  { id: "d5d-014", en: "mourning", pt: "luto", category: "Connection - 5 - D" },
  {
    id: "d5d-015",
    en: "gathering",
    pt: "reunião, encontro",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-016",
    en: "mourners",
    pt: "pessoas de luto",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-017",
    en: "had discussed",
    pt: "havia discutido",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-018",
    en: "foundation",
    pt: "fundação",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-019",
    en: "charitable",
    pt: "de caridade",
    category: "Connection - 5 - D",
  },
  { id: "d5d-020", en: "desire", pt: "desejo", category: "Connection - 5 - D" },
  {
    id: "d5d-021",
    en: "fortunate",
    pt: "afortunado",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-022",
    en: "effective",
    pt: "efetivo, eficaz",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-023",
    en: "set up",
    pt: "estabeleceu, fundou",
    category: "Connection - 5 - D",
  },
  {
    id: "d5d-024",
    en: "honor",
    pt: "honra, homenagem",
    category: "Connection - 5 - D",
  },
];
